//! App workspace scaffolding for `temper init`.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

const CSDL_TEMPLATE: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="{{namespace}}" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="Item">
        <Key><PropertyRef Name="Id"/></Key>
        <Property Name="Id" Type="Edm.Guid" Nullable="false"/>
        <Property Name="Name" Type="Edm.String" Nullable="false"/>
        <Property Name="Status" Type="Edm.String" Nullable="false"/>
      </EntityType>
      <Action Name="Complete" IsBound="true">
        <Parameter Name="bindingParameter" Type="{{namespace}}.Item" Nullable="false"/>
      </Action>
      <EntityContainer Name="Service">
        <EntitySet Name="Items" EntityType="{{namespace}}.Item"/>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
"#;

const IOA_TEMPLATE: &str = r#"[automaton]
name = "Item"
states = ["Open", "Done"]
initial = "Open"

[[action]]
name = "Complete"
kind = "input"
from = ["Open"]
to = "Done"

[[invariant]]
name = "DoneIsTerminal"
when = ["Done"]
assert = "no_further_transitions"
"#;

const APP_GUIDE_TEMPLATE: &str = r#"# {{title}}

A local-first Temper app generated by `temper init`.

## Entity types

### Item

Items begin in `Open` and support the `Complete` action.

## Local development

Run `temper dev` from this directory. Temper verifies and promotes each valid
immutable revision while leaving the last valid revision active after errors.
"#;

const CEDAR_TEMPLATE: &str = r#"permit(
  principal is Agent,
  action in [Action::"create", Action::"read", Action::"list", Action::"Complete"],
  resource is Item
) when {
  principal.agent_type == "operator" &&
  principal.agentTypeVerified == true
};
"#;

/// Run `temper init <name>` and create an installable local app workspace.
pub fn run(name: &str) -> Result<()> {
    let root = Path::new(name);
    if root.exists() {
        anyhow::bail!("Directory '{}' already exists", name);
    }
    let app_name = root
        .file_name()
        .and_then(|value| value.to_str())
        .filter(|value| !value.is_empty())
        .context("project name must end in a valid UTF-8 path component")?;

    println!("Initializing Temper app '{app_name}'...");
    let specs = root.join("specs");
    fs::create_dir_all(&specs)
        .with_context(|| format!("Failed to create directory: {}", specs.display()))?;
    fs::create_dir_all(root.join("policies")).with_context(|| {
        format!(
            "Failed to create directory: {}",
            root.join("policies").display()
        )
    })?;

    let namespace = to_namespace(app_name);
    write(
        &root.join("app.toml"),
        &format!(
            "name = {app_name:?}\ndescription = \"A local-first Temper app\"\nversion = \"0.1.0\"\n"
        ),
    )?;
    write(
        &root.join("APP.md"),
        &APP_GUIDE_TEMPLATE.replace("{{title}}", &namespace.replace("Temper.", "")),
    )?;
    write(
        &root.join("temper.lock.toml"),
        "version = 1\nentries = []\n",
    )?;
    write(
        &specs.join("model.csdl.xml"),
        &CSDL_TEMPLATE.replace("{{namespace}}", &namespace),
    )?;
    write(&specs.join("item.ioa.toml"), IOA_TEMPLATE)?;
    write(&root.join("policies/local.cedar"), CEDAR_TEMPLATE)?;

    println!("\nApp '{app_name}' initialized successfully.");
    println!("Next: cd {name} && temper dev");
    Ok(())
}

fn write(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content).with_context(|| format!("Failed to write {}", path.display()))?;
    println!("  Wrote {}", path.display());
    Ok(())
}

fn to_namespace(name: &str) -> String {
    let pascal: String = name
        .split(['-', '_'])
        .map(|word| {
            let mut chars = word.chars();
            chars.next().map_or_else(String::new, |first| {
                format!("{}{}", first.to_uppercase(), chars.collect::<String>())
            })
        })
        .collect();
    format!("Temper.{pascal}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn namespace_is_pascal_case() {
        assert_eq!(to_namespace("my-app"), "Temper.MyApp");
        assert_eq!(to_namespace("hello_world"), "Temper.HelloWorld");
    }

    #[test]
    fn init_creates_installable_workspace() {
        let temporary = tempfile::tempdir().unwrap();
        let project = temporary.path().join("my-app");
        run(project.to_str().unwrap()).unwrap();

        assert!(project.join("app.toml").is_file());
        assert!(project.join("APP.md").is_file());
        assert!(project.join("temper.lock.toml").is_file());
        assert!(project.join("specs/model.csdl.xml").is_file());
        assert!(project.join("specs/item.ioa.toml").is_file());
        assert!(project.join("policies/local.cedar").is_file());
        assert!(!project.join("Cargo.toml").exists());
        let manifest = fs::read_to_string(project.join("app.toml")).unwrap();
        assert!(manifest.contains("name = \"my-app\""));
    }

    #[test]
    fn init_rejects_existing_directory() {
        let project = tempfile::tempdir().unwrap();
        let error = run(project.path().to_str().unwrap()).unwrap_err();
        assert!(error.to_string().contains("already exists"));
    }
}
