//! Deterministic, capability-scoped Rust client generation for WASM modules.

use std::collections::{BTreeMap, BTreeSet};

use temper_spec::CanonicalSpecModel;
use temper_spec::csdl::{Action, CsdlDocument, EntityType, emit_csdl_xml};
use temper_wasm_sdk::data::{
    DataOperationKind, EntityDataGrant, ManifestActionResultCardinalityV1, ManifestActionV1,
    ManifestEntityV1, ManifestPropertyV1, ManifestValueSourceV1, ModuleDataGrant,
    ModuleSdkManifest, ModuleSdkMetadataDigests,
};

mod defaults;
mod entity_results;
mod legacy;
mod names;
mod packaging;
mod property_sources;
mod schema_helpers;
mod source_types;
mod stream_capabilities;
mod types;
use defaults::manifest_property;
use entity_results::{emit_entity_value_types, generated_entity_names, validate_entity_results};
use names::{checked_enum_variant, reject_generated_collisions, rust_field_name};
pub use packaging::package_generated_module_sdk;
use property_sources::assign_entity_property_sources;
use schema_helpers::{entity_sets, enum_members};
use source_types::{
    emit_artifact_binding, emit_named_property_type, hex_sha256, register_generated_type,
};
use stream_capabilities::stream_capabilities_for_grant;
mod client_emitter;
use client_emitter::{EntityClientSpec, emit_entity_client};
pub use types::{GeneratedModuleSdk, ModuleSdkCodegenError, PackagedModuleSdk};

/// Generate a module-specific Rust client from a verified closure and exact grant.
pub fn generate_module_sdk(
    model: &CanonicalSpecModel,
    module_name: &str,
    closure_digest: &str,
    dependency_lock_digest: &str,
    artifact_digest: &str,
    grant: ModuleDataGrant,
) -> Result<GeneratedModuleSdk, ModuleSdkCodegenError> {
    generate_module_sdk_impl(
        model,
        module_name,
        closure_digest,
        dependency_lock_digest,
        artifact_digest,
        grant,
        true,
    )
}

/// Regenerate a persisted v1 binding with its frozen lifecycle inference and ABI shape.
pub fn generate_module_sdk_v1(
    csdl: &CsdlDocument,
    ioa_sources: &[temper_spec::bundle::IoaSourceInput],
    module_name: &str,
    closure_digest: &str,
    dependency_lock_digest: &str,
    artifact_digest: &str,
    grant: ModuleDataGrant,
) -> Result<GeneratedModuleSdk, ModuleSdkCodegenError> {
    let model = legacy::model_v1(csdl, ioa_sources)?;
    generate_module_sdk_impl(
        &model,
        module_name,
        closure_digest,
        dependency_lock_digest,
        artifact_digest,
        grant,
        false,
    )
}

fn generate_module_sdk_impl(
    model: &CanonicalSpecModel,
    module_name: &str,
    closure_digest: &str,
    dependency_lock_digest: &str,
    artifact_digest: &str,
    grant: ModuleDataGrant,
    include_lifecycle_contract: bool,
) -> Result<GeneratedModuleSdk, ModuleSdkCodegenError> {
    let csdl = model.emitted_csdl();
    grant
        .validate()
        .map_err(ModuleSdkCodegenError::InvalidGrant)?;
    let schema_digest = hex_sha256(emit_csdl_xml(csdl).as_bytes());
    let stream_capabilities = stream_capabilities_for_grant(csdl, &grant)?;
    let entity_sets = entity_sets(csdl);
    validate_entity_results(csdl, &grant)?;
    let generated_entity_names = generated_entity_names(csdl, &grant)?;
    let mut entities = Vec::new();
    let mut used_symbols = BTreeSet::new();
    let mut generated_named_types = BTreeMap::new();
    for (canonical, generated) in &generated_entity_names {
        register_generated_type(
            &mut generated_named_types,
            generated.clone(),
            format!("entity type '{canonical}'"),
        )?;
        register_generated_type(
            &mut generated_named_types,
            format!("{generated}Id"),
            format!("entity ID type for '{canonical}'"),
        )?;
    }
    let mut source = String::from(
        "// @generated by temper-codegen; do not edit.\nuse temper_wasm_sdk::data::*;\n\n",
    );

    let mut entity_grants = grant.entities.iter().collect::<Vec<_>>();
    entity_grants.sort_by(|left, right| left.entity_type.cmp(&right.entity_type));
    for entity_grant in entity_grants {
        let (entity, actions) = resolve_entity(csdl, entity_grant)?;
        let entity_set = entity_sets
            .get(entity_grant.entity_type.as_str())
            .ok_or_else(|| {
                ModuleSdkCodegenError::MissingEntitySet(entity_grant.entity_type.clone())
            })?;
        let generated = generated_entity_names
            .get(&entity_grant.entity_type)
            .expect("granted entity must have a generated name")
            .clone();
        used_symbols.insert(entity_grant.entity_type.clone());
        used_symbols.insert(entity_set.to_string());
        let entity_value_required = [
            DataOperationKind::EntityGet,
            DataOperationKind::EntityQuery,
            DataOperationKind::EntityCreate,
            DataOperationKind::EntityCreateOrVerify,
            DataOperationKind::EntityPatch,
        ]
        .into_iter()
        .any(|operation| grant.permits(operation, &entity_grant.entity_type, None))
            || actions.iter().any(|action| {
                granted_action_operation(&grant, entity_grant, &action.name).is_some()
                    && action
                        .return_type
                        .as_ref()
                        .is_some_and(|result| result.type_name == entity_grant.entity_type)
            });
        let mut properties = if entity_value_required {
            entity
                .properties
                .iter()
                .map(|property| {
                    manifest_property(
                        csdl,
                        &property.name,
                        &property.type_name,
                        property.nullable,
                        property.default_value.as_deref(),
                        ManifestValueSourceV1::StoredField,
                    )
                })
                .collect::<Result<Vec<_>, _>>()?
        } else {
            Vec::new()
        };
        let lifecycle_states = if entity_value_required {
            assign_entity_property_sources(
                model,
                &entity_grant.entity_type,
                entity,
                &mut properties,
            )?
        } else {
            model
                .behavioral_entity(&entity_grant.entity_type)
                .map(|entity| entity.lifecycle_states().to_vec())
                .unwrap_or_default()
        };
        if include_lifecycle_contract {
            for state in &lifecycle_states {
                used_symbols.insert(format!("lifecycle:{}:{state}", entity_grant.entity_type));
            }
        }
        for property in &properties {
            used_symbols.insert(format!(
                "property:{}:{}",
                entity_grant.entity_type, property.canonical_name
            ));
            used_symbols.insert(format!("type:{}", property.type_name));
            for member in &property.enum_members {
                used_symbols.insert(format!("enum:{}:{member}", property.type_name));
            }
        }
        reject_generated_collisions(
            &entity_grant.entity_type,
            properties
                .iter()
                .map(|property| (&property.canonical_name, &property.generated_name)),
        )?;
        let string_lifecycle_type = (include_lifecycle_contract
            && properties.iter().any(|property| {
                property.source == ManifestValueSourceV1::LifecycleStatus
                    && property.type_name == "Edm.String"
            }))
        .then(|| format!("{generated}LifecycleState"));
        if let Some(type_name) = &string_lifecycle_type {
            let owner = format!("string lifecycle type for '{}'", entity_grant.entity_type);
            register_generated_type(&mut generated_named_types, type_name.clone(), owner)?;
            source.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]\npub enum {type_name} {{\n"
            ));
            let mut generated_members = BTreeSet::new();
            for state in &lifecycle_states {
                let member = checked_enum_variant(type_name, state)?;
                if !generated_members.insert(member.clone()) {
                    return Err(ModuleSdkCodegenError::IdentifierCollision(format!(
                        "{type_name}::{member}"
                    )));
                }
                source.push_str(&format!(
                    "    #[serde(rename = {})]\n    {member},\n",
                    format_args!("{state:?}")
                ));
            }
            source.push_str("}\n\n");
        }
        if entity_grant.query_order_by_sequence
            && properties.iter().any(|property| {
                entity_grant
                    .query_order_fields
                    .contains(&property.canonical_name)
                    && property.generated_name == "commit_sequence"
            })
        {
            return Err(ModuleSdkCodegenError::IdentifierCollision(format!(
                "{}: query property and host commit-sequence helper both generate 'commit_sequence'",
                entity_grant.entity_type
            )));
        }
        let manifest_actions = actions
            .into_iter()
            .filter(|action| granted_action_operation(&grant, entity_grant, &action.name).is_some())
            .map(
                |action| -> Result<ManifestActionV1, ModuleSdkCodegenError> {
                    used_symbols.insert(action.name.clone());
                    let manifest_action = ManifestActionV1 {
                        canonical_name: action.name.clone(),
                        generated_name: rust_field_name(&action.name),
                        parameters: action
                            .parameters
                            .iter()
                            .skip(1)
                            .map(|parameter| {
                                manifest_property(
                                    csdl,
                                    &parameter.name,
                                    &parameter.type_name,
                                    parameter.nullable,
                                    parameter.default_value.as_deref(),
                                    ManifestValueSourceV1::Input,
                                )
                            })
                            .collect::<Result<Vec<_>, _>>()?,
                        result_type: action
                            .return_type
                            .as_ref()
                            .map(|result| result.type_name.clone()),
                        result_enum_members: action
                            .return_type
                            .as_ref()
                            .map(|result| enum_members(csdl, &result.type_name))
                            .unwrap_or_default(),
                        result_cardinality: Some(match &action.return_type {
                            None => ManifestActionResultCardinalityV1::Void,
                            Some(result) if result.nullable => {
                                ManifestActionResultCardinalityV1::Nullable
                            }
                            Some(_) => ManifestActionResultCardinalityV1::Required,
                        }),
                        composite: entity_grant.composite_actions.contains(&action.name),
                    };
                    for parameter in &manifest_action.parameters {
                        used_symbols.insert(format!(
                            "parameter:{}:{}:{}",
                            entity_grant.entity_type, action.name, parameter.canonical_name
                        ));
                        used_symbols.insert(format!("type:{}", parameter.type_name));
                        for member in &parameter.enum_members {
                            used_symbols.insert(format!("enum:{}:{member}", parameter.type_name));
                        }
                    }
                    if let Some(result_type) = &manifest_action.result_type {
                        used_symbols.insert(format!("result:{}:{}", action.name, result_type));
                        used_symbols.insert(format!("type:{result_type}"));
                        for member in &manifest_action.result_enum_members {
                            used_symbols.insert(format!("enum:{result_type}:{member}"));
                        }
                    }
                    Ok(manifest_action)
                },
            )
            .collect::<Result<Vec<_>, _>>()?;
        reject_generated_collisions(
            &entity_grant.entity_type,
            manifest_actions
                .iter()
                .map(|action| (&action.canonical_name, &action.generated_name)),
        )?;
        if entity_value_required {
            for property in &properties {
                emit_named_property_type(&mut source, property, &mut generated_named_types)?;
            }
        }
        for action in &manifest_actions {
            for parameter in &action.parameters {
                emit_named_property_type(&mut source, parameter, &mut generated_named_types)?;
            }
            if let Some(type_name) = &action.result_type
                && !generated_entity_names.contains_key(type_name)
            {
                emit_named_property_type(
                    &mut source,
                    &ManifestPropertyV1 {
                        canonical_name: "result".into(),
                        generated_name: "result".into(),
                        type_name: type_name.clone(),
                        nullable: false,
                        source: ManifestValueSourceV1::Input,
                        default_value: None,
                        enum_members: action.result_enum_members.clone(),
                        write_policy: None,
                    },
                    &mut generated_named_types,
                )?;
            }
        }
        if entity_value_required {
            emit_entity_value_types(
                &mut source,
                &generated,
                &properties,
                string_lifecycle_type.as_deref(),
            );
        }
        emit_entity_client(
            &mut source,
            EntityClientSpec {
                generated: &generated,
                canonical: &entity_grant.entity_type,
                properties: &properties,
                actions: &manifest_actions,
                grant: &grant,
                entity_grant,
                generated_entity_names: &generated_entity_names,
                string_lifecycle_type: string_lifecycle_type.as_deref(),
            },
        );
        entities.push(ManifestEntityV1 {
            entity_type: entity_grant.entity_type.clone(),
            entity_set: entity_set.to_string(),
            generated_name: generated,
            lifecycle_states: if include_lifecycle_contract {
                lifecycle_states
            } else {
                Vec::new()
            },
            properties,
            actions: manifest_actions,
        });
    }
    entities.sort_by(|left, right| left.entity_type.cmp(&right.entity_type));
    if grant.operations.contains(&DataOperationKind::Batch) {
        source.push_str("pub fn execute_batch(data: &mut DataClient, items: Vec<BatchItemV1>) -> Result<DataResultV1, ModuleDataError> { data.call(DataOperationV1::Batch { items }) }\n\n");
    }
    let mut manifest = ModuleSdkManifest::new(
        module_name,
        ModuleSdkMetadataDigests {
            closure: closure_digest.into(),
            dependency_lock: dependency_lock_digest.into(),
            schema: schema_digest,
        },
        artifact_digest,
        grant,
        entities,
        used_symbols,
    )
    .map_err(ModuleSdkCodegenError::Manifest)?;
    manifest.stream_capabilities = stream_capabilities;
    if !include_lifecycle_contract {
        manifest.contract_version = None;
        for entity in &mut manifest.entities {
            for property in &mut entity.properties {
                property.write_policy = None;
            }
            for action in &mut entity.actions {
                action.result_cardinality = None;
            }
        }
    }
    emit_artifact_binding(&mut source, &manifest);
    Ok(GeneratedModuleSdk { source, manifest })
}

fn granted_action_operation(
    grant: &ModuleDataGrant,
    entity: &EntityDataGrant,
    action: &str,
) -> Option<DataOperationKind> {
    if entity.composite_actions.contains(action)
        && grant.permits(
            DataOperationKind::CompositeInvoke,
            &entity.entity_type,
            Some(action),
        )
    {
        return Some(DataOperationKind::CompositeInvoke);
    }
    if entity.actions.contains(action)
        && grant.permits(
            DataOperationKind::ActionInvoke,
            &entity.entity_type,
            Some(action),
        )
    {
        return Some(DataOperationKind::ActionInvoke);
    }
    None
}

fn resolve_entity<'a>(
    csdl: &'a CsdlDocument,
    grant: &EntityDataGrant,
) -> Result<(&'a EntityType, Vec<&'a Action>), ModuleSdkCodegenError> {
    let (namespace, name) = grant
        .entity_type
        .rsplit_once('.')
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    let schema = csdl
        .schemas
        .iter()
        .find(|schema| schema.namespace == namespace)
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    let entity = schema
        .entity_type(name)
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    if !grant.file_operations.is_empty() && (name != "File" || !entity.has_stream) {
        return Err(ModuleSdkCodegenError::MissingSymbol {
            entity_type: grant.entity_type.clone(),
            symbol: "File content capability on a HasStream File entity".into(),
        });
    }
    for field in grant
        .query_filter_fields
        .iter()
        .chain(&grant.query_order_fields)
    {
        if !entity
            .properties
            .iter()
            .any(|property| property.name == *field)
        {
            return Err(ModuleSdkCodegenError::MissingSymbol {
                entity_type: grant.entity_type.clone(),
                symbol: field.clone(),
            });
        }
    }
    let mut actions = Vec::new();
    for name in grant.actions.iter().chain(&grant.composite_actions) {
        let matches = schema.bound_actions(name, &grant.entity_type);
        let action = match matches.as_slice() {
            [] => {
                return Err(ModuleSdkCodegenError::MissingSymbol {
                    entity_type: grant.entity_type.clone(),
                    symbol: name.clone(),
                });
            }
            [action] => *action,
            _ => {
                return Err(ModuleSdkCodegenError::AmbiguousBoundAction {
                    entity_type: grant.entity_type.clone(),
                    action: name.clone(),
                    matches: matches.len(),
                });
            }
        };
        actions.push(action);
    }
    actions.sort_by(|left, right| left.name.cmp(&right.name));
    Ok((entity, actions))
}

#[cfg(test)]
mod default_tests;
#[cfg(test)]
mod property_sources_tests;
#[cfg(test)]
mod tests;
