//! Deterministic, capability-scoped Rust client generation for WASM modules.

use std::collections::BTreeSet;

use temper_spec::csdl::{Action, CsdlDocument, EntityType, emit_csdl_xml};
use temper_wasm_sdk::data::{
    ArtifactModuleSdkBinding, EntityDataGrant, ManifestActionV1, ManifestEntityV1,
    ManifestPropertyV1, ModuleDataGrant, ModuleSdkManifest, ModuleSdkMetadataDigests,
    bind_module_sdk_artifact,
};

mod entity_results;
mod names;
mod schema_helpers;
mod source_types;
mod types;
use entity_results::{emit_entity_value_types, generated_entity_names, validate_entity_results};
use names::{reject_generated_collisions, rust_field_name};
use schema_helpers::{entity_sets, enum_members};
use source_types::{emit_artifact_binding, emit_named_property_type, hex_sha256};
mod client_emitter;
use client_emitter::{EntityClientSpec, emit_entity_client};
pub use types::{GeneratedModuleSdk, PackagedModuleSdk};

/// A fail-closed schema or naming error during module SDK generation.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum ModuleSdkCodegenError {
    #[error("invalid module data grant: {0}")]
    InvalidGrant(String),
    #[error("granted entity type '{0}' is absent from the verified CSDL closure")]
    MissingEntity(String),
    #[error("entity type '{0}' has no entity set in the verified CSDL closure")]
    MissingEntitySet(String),
    #[error("granted schema symbol '{symbol}' is absent from entity '{entity_type}'")]
    MissingSymbol { entity_type: String, symbol: String },
    #[error("generated Rust identifier collision '{0}'")]
    IdentifierCollision(String),
    #[error(
        "bound action '{action}' on '{entity_type}' returns different entity type '{result_type}'"
    )]
    UnsupportedEntityResult {
        action: String,
        entity_type: String,
        result_type: String,
    },
    #[error("failed to construct module SDK manifest: {0}")]
    Manifest(String),
    #[error("failed to bind compiled module artifact: {0}")]
    ArtifactBinding(String),
}

/// Bind generated metadata into compiled WebAssembly and finalize its digest.
///
/// Build tooling calls this after compiling [`GeneratedModuleSdk::source`] and
/// before constructing the published application bundle.
pub fn package_generated_module_sdk(
    wasm: &[u8],
    mut generated: GeneratedModuleSdk,
) -> Result<PackagedModuleSdk, ModuleSdkCodegenError> {
    let binding = ArtifactModuleSdkBinding::from_manifest(&generated.manifest)
        .map_err(ModuleSdkCodegenError::ArtifactBinding)?;
    let wasm =
        bind_module_sdk_artifact(wasm, &binding).map_err(ModuleSdkCodegenError::ArtifactBinding)?;
    generated.manifest.artifact_digest = hex_sha256(&wasm);
    Ok(PackagedModuleSdk {
        wasm,
        manifest: generated.manifest,
    })
}

/// Generate a module-specific Rust client from a verified closure and exact grant.
pub fn generate_module_sdk(
    csdl: &CsdlDocument,
    module_name: &str,
    closure_digest: &str,
    dependency_lock_digest: &str,
    artifact_digest: &str,
    grant: ModuleDataGrant,
) -> Result<GeneratedModuleSdk, ModuleSdkCodegenError> {
    grant
        .validate()
        .map_err(ModuleSdkCodegenError::InvalidGrant)?;
    let schema_digest = hex_sha256(emit_csdl_xml(csdl).as_bytes());
    let entity_sets = entity_sets(csdl);
    validate_entity_results(csdl, &grant)?;
    let generated_entity_names = generated_entity_names(csdl, &grant)?;
    let mut entities = Vec::new();
    let mut used_symbols = BTreeSet::new();
    let mut generated_named_types = BTreeSet::new();
    let mut source = String::from(
        "// @generated by temper-codegen; do not edit.\nuse temper_wasm_sdk::data::*;\n\nfn invalid_generated_value(error: serde_json::Error) -> ModuleDataError { ModuleDataError::new(ModuleDataErrorKind::InvalidRequest, \"GeneratedValueEncodingFailed\", error.to_string(), Retryability::Never) }\n\n",
    );

    let mut entity_grants = grant.entities.iter().collect::<Vec<_>>();
    entity_grants.sort_by(|left, right| left.entity_type.cmp(&right.entity_type));
    for entity_grant in entity_grants {
        let (entity, actions) = resolve_entity(csdl, entity_grant)?;
        let entity_set = entity_sets
            .get(entity_grant.entity_type.as_str())
            .ok_or_else(|| {
                ModuleSdkCodegenError::MissingEntitySet(entity_grant.entity_type.clone())
            })?;
        let generated = generated_entity_names
            .get(&entity_grant.entity_type)
            .expect("granted entity must have a generated name")
            .clone();
        used_symbols.insert(entity_grant.entity_type.clone());
        used_symbols.insert(entity_set.to_string());
        let properties = entity
            .properties
            .iter()
            .map(|property| ManifestPropertyV1 {
                canonical_name: property.name.clone(),
                generated_name: rust_field_name(&property.name),
                type_name: property.type_name.clone(),
                nullable: property.nullable,
                enum_members: enum_members(csdl, &property.type_name),
            })
            .collect::<Vec<_>>();
        for property in &properties {
            used_symbols.insert(format!(
                "property:{}:{}",
                entity_grant.entity_type, property.canonical_name
            ));
            used_symbols.insert(format!("type:{}", property.type_name));
            for member in &property.enum_members {
                used_symbols.insert(format!("enum:{}:{member}", property.type_name));
            }
        }
        reject_generated_collisions(
            &entity_grant.entity_type,
            properties
                .iter()
                .map(|property| (&property.canonical_name, &property.generated_name)),
        )?;
        if entity_grant.query_order_by_sequence
            && properties.iter().any(|property| {
                entity_grant
                    .query_order_fields
                    .contains(&property.canonical_name)
                    && property.generated_name == "commit_sequence"
            })
        {
            return Err(ModuleSdkCodegenError::IdentifierCollision(format!(
                "{}: query property and host commit-sequence helper both generate 'commit_sequence'",
                entity_grant.entity_type
            )));
        }
        let manifest_actions = actions
            .into_iter()
            .map(|action| {
                used_symbols.insert(action.name.clone());
                let manifest_action = ManifestActionV1 {
                    canonical_name: action.name.clone(),
                    generated_name: rust_field_name(&action.name),
                    parameters: action
                        .parameters
                        .iter()
                        .skip(1)
                        .map(|parameter| ManifestPropertyV1 {
                            canonical_name: parameter.name.clone(),
                            generated_name: rust_field_name(&parameter.name),
                            type_name: parameter.type_name.clone(),
                            nullable: parameter.nullable,
                            enum_members: enum_members(csdl, &parameter.type_name),
                        })
                        .collect(),
                    result_type: action
                        .return_type
                        .as_ref()
                        .map(|result| result.type_name.clone()),
                    result_enum_members: action
                        .return_type
                        .as_ref()
                        .map(|result| enum_members(csdl, &result.type_name))
                        .unwrap_or_default(),
                    composite: entity_grant.composite_actions.contains(&action.name),
                };
                for parameter in &manifest_action.parameters {
                    used_symbols.insert(format!(
                        "parameter:{}:{}:{}",
                        entity_grant.entity_type, action.name, parameter.canonical_name
                    ));
                    used_symbols.insert(format!("type:{}", parameter.type_name));
                    for member in &parameter.enum_members {
                        used_symbols.insert(format!("enum:{}:{member}", parameter.type_name));
                    }
                }
                if let Some(result_type) = &manifest_action.result_type {
                    used_symbols.insert(format!("result:{}:{}", action.name, result_type));
                    used_symbols.insert(format!("type:{result_type}"));
                    for member in &manifest_action.result_enum_members {
                        used_symbols.insert(format!("enum:{result_type}:{member}"));
                    }
                }
                manifest_action
            })
            .collect::<Vec<_>>();
        reject_generated_collisions(
            &entity_grant.entity_type,
            manifest_actions
                .iter()
                .map(|action| (&action.canonical_name, &action.generated_name)),
        )?;
        for property in &properties {
            emit_named_property_type(&mut source, property, &mut generated_named_types);
        }
        for action in &manifest_actions {
            for parameter in &action.parameters {
                emit_named_property_type(&mut source, parameter, &mut generated_named_types);
            }
            if let Some(type_name) = &action.result_type
                && !generated_entity_names.contains_key(type_name)
            {
                emit_named_property_type(
                    &mut source,
                    &ManifestPropertyV1 {
                        canonical_name: "result".into(),
                        generated_name: "result".into(),
                        type_name: type_name.clone(),
                        nullable: false,
                        enum_members: action.result_enum_members.clone(),
                    },
                    &mut generated_named_types,
                );
            }
        }
        emit_entity_value_types(&mut source, &generated, &properties);
        emit_entity_client(
            &mut source,
            EntityClientSpec {
                generated: &generated,
                canonical: &entity_grant.entity_type,
                properties: &properties,
                actions: &manifest_actions,
                grant: &grant,
                entity_grant,
                generated_entity_names: &generated_entity_names,
            },
        );
        entities.push(ManifestEntityV1 {
            entity_type: entity_grant.entity_type.clone(),
            entity_set: entity_set.to_string(),
            generated_name: generated,
            properties,
            actions: manifest_actions,
        });
    }
    entities.sort_by(|left, right| left.entity_type.cmp(&right.entity_type));
    if grant
        .operations
        .contains(&temper_wasm_sdk::data::DataOperationKind::Batch)
    {
        source.push_str("pub fn execute_batch(data: &mut DataClient, items: Vec<BatchItemV1>) -> Result<DataResultV1, ModuleDataError> { data.call(DataOperationV1::Batch { items }) }\n\n");
    }
    let manifest = ModuleSdkManifest::new(
        module_name,
        ModuleSdkMetadataDigests {
            closure: closure_digest.into(),
            dependency_lock: dependency_lock_digest.into(),
            schema: schema_digest,
        },
        artifact_digest,
        grant,
        entities,
        used_symbols,
    )
    .map_err(ModuleSdkCodegenError::Manifest)?;
    emit_artifact_binding(&mut source, &manifest);
    Ok(GeneratedModuleSdk { source, manifest })
}

fn resolve_entity<'a>(
    csdl: &'a CsdlDocument,
    grant: &EntityDataGrant,
) -> Result<(&'a EntityType, Vec<&'a Action>), ModuleSdkCodegenError> {
    let (namespace, name) = grant
        .entity_type
        .rsplit_once('.')
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    let schema = csdl
        .schemas
        .iter()
        .find(|schema| schema.namespace == namespace)
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    let entity = schema
        .entity_type(name)
        .ok_or_else(|| ModuleSdkCodegenError::MissingEntity(grant.entity_type.clone()))?;
    if !grant.file_operations.is_empty() && (name != "File" || !entity.has_stream) {
        return Err(ModuleSdkCodegenError::MissingSymbol {
            entity_type: grant.entity_type.clone(),
            symbol: "File content capability on a HasStream File entity".into(),
        });
    }
    for field in grant
        .query_filter_fields
        .iter()
        .chain(&grant.query_order_fields)
    {
        if !entity
            .properties
            .iter()
            .any(|property| property.name == *field)
        {
            return Err(ModuleSdkCodegenError::MissingSymbol {
                entity_type: grant.entity_type.clone(),
                symbol: field.clone(),
            });
        }
    }
    let mut actions = Vec::new();
    for name in grant.actions.iter().chain(&grant.composite_actions) {
        let action = schema
            .action(name)
            .ok_or_else(|| ModuleSdkCodegenError::MissingSymbol {
                entity_type: grant.entity_type.clone(),
                symbol: name.clone(),
            })?;
        let bound_type = action
            .parameters
            .first()
            .map(|parameter| parameter.type_name.as_str());
        if !action.is_bound || bound_type != Some(grant.entity_type.as_str()) {
            return Err(ModuleSdkCodegenError::MissingSymbol {
                entity_type: grant.entity_type.clone(),
                symbol: name.clone(),
            });
        }
        actions.push(action);
    }
    actions.sort_by(|left, right| left.name.cmp(&right.name));
    Ok((entity, actions))
}

#[cfg(test)]
mod tests;
